# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true

# Fabric Properties
minecraft_version=1.20.1
yarn_mappings=1.20.1+build.10
loader_version=0.19.2
loom_version=1.16-SNAPSHOT

fabric_api_version=0.92.8+1.20.1

# Mod Properties
mod_id=moredelight
mod_name=More Delight
mod_license=MIT
mod_version=26.05.07a-1.20-fabric
mod_authors=Axperty
mod_description=An addon mod for Farmer's Delight that adds extra features to the base mod.
maven_group=com.axperty
archives_base_name=moredelight