# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true

# Fabric Properties
minecraft_version=1.21.1
yarn_mappings=1.21.1+build.3
loader_version=0.16.14
loom_version=1.11-SNAPSHOT

fabric_version=0.116.4+1.21.1

# Mod Properties
modid = moredelight
mod_version = 25.07.28-1.21-fabric
maven_group = com.axperty
archives_base_name = moredelight

# Dependencies
fdfr_version=1.21.1-3.1.2+refabricated
jei_version=15.3.0.4