# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true

# Fabric Properties
minecraft_version=26.2
loader_version=0.19.3
loom_version=1.17-SNAPSHOT

# Mod Properties
mod_id=moredelight
mod_name=More Delight
mod_license=MIT
mod_version=26.06.23-26.2-fabric
mod_authors=Axperty
mod_description=An addon mod for Farmer's Delight that adds extra features to the base mod.
maven_group=com.axperty
archives_base_name=moredelight

# Dependencies
fabric_api_version=0.152.2+26.2